apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 300Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce