pipeline {
  agent any

  stages {
    stage('Compile') {
      steps {
        dir('./03-ci/01-jenkins') {
          echo "Building source code"
          sh '''
            chmod +x ./gradlew
            ./gradlew
          '''
        }
      }
    }
    stage('Unit Test') {
      steps {
        dir('./03-ci/01-jenkins') {
          echo "Testing source code"
          sh '''
            './gradlew test'
          '''
        }
      }
    }
  }
}